# site settings
title: AI Risk Discussions
subtitle: 
email: vaelgates@gmail.com
description: AI Risk Discussions aims to facilitate discussion and evaluation of potential risks from advanced AI. Our focus is on soliciting and engaging with expert perspectives of the arguments, and providing resources for stakeholders.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ai-risk-discussions.org # the base hostname & protocol for your site
author:

permalink: /:title

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- /tools/*
