name: Download papers metadata from Airtable
concurrency: download-airtable-papers-metadata

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  downloaddata:
    env:
      GIT_TERMINAL_PROMPT: 0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    - run: pip install airtable-export
    - run: airtable-export --json export ${{ secrets.AIRTABLE_BASE_ID }} ${{ secrets.AIRTABLE_TABLE }} --key ${{ secrets.AIRTABLE_KEY }}

    # Step to check if the file has changed
    - name: Check if the table data has changed
      id: file-check
      run: |
        if test -f export/${{ secrets.AIRTABLE_TABLE }}.json; then
          if cmp -s export/${{ secrets.AIRTABLE_TABLE }}.json export/papers.json; then
            echo "No changes in papers.json, aborting job."
            echo "::set-output name=changed::false"
          else
            echo "Changes detected in papers.json."
            echo "::set-output name=changed::true"
          fi
        else
          echo "papers.json does not exist, proceeding with job."
          echo "::set-output name=changed::true"
        fi

    # Conditionally execute the remaining steps
    - if: steps.file-check.outputs.changed == 'true'
      run: |
        rm export/papers.json
        jq 'del(.[] | ."Reviewed by", ."Vael'\''s Notes", ."Internal source", ."Who tagged for ML", ."airtable_createdTime", ."airtable_id")' export/${{ secrets.AIRTABLE_TABLE }}.json > export/papers.json
        git status

    - if: steps.file-check.outputs.changed == 'true'
      run: |
        git config user.name "Michael Keenan"
        git config user.email "michael.keenan@gmail.com"

    - if: steps.file-check.outputs.changed == 'true'
      run: |
        git add export/papers.json

    - if: steps.file-check.outputs.changed == 'true'
      run: |
        git commit -v -m "Update papers.json"

    - if: steps.file-check.outputs.changed == 'true'
      run: |
        git push
